Module9 task1
htmlacademy-javascript/2073541-keksobooking-27 pull request #9
Opened 2022-10-31 16:37 UTC by shuriksl

2022-11-01 13:57 UTC, craz3r requested changes
Когда страница загружается то в плейсхолдере цены записано значение 5000 для типа жилья "квартира", но при этом когда редактируется поле "цена" с помощью слайдера, валидационное сообщение говорит что минимальная цена за квартиру - 1000.

2022-11-01 13:57 UTC, craz3r commented on js/map.js
> +map.on('load', activatePage(true));
На момент первичной загрузки страницы она должна быть заблокирована, но вызова activatePage(false) нигде нет

2022-11-01 13:57 UTC, craz3r commented on js/map.js
> +addressField.value = `lat: ${mainMarker.getLatLng().lat} lng: ${mainMarker.getLatLng().lng}`;
Поле адрес должно содержать только координаты через запятую, без lat:, lng:

2022-11-01 20:12 UTC, shuriksl commented on js/map.js
> +map.on('load', activatePage(true));
Добавила в модуль page-disable.js

2022-11-02 08:03 UTC, craz3r commented on js/page-disable.js
> +activatePage(false);
Из за того что ты импортируешь только функцию activatePage из модуля, код в 26й строке не выполнится

2022-11-02 08:03 UTC, merged